[SERVICE]
    Flush        1
    Log_Level    info
    Parsers_File parsers.conf

[INPUT]
    Name   forward
    Listen 0.0.0.0
    Port   24224

[FILTER]
    name parser
    match *
    key_name log
    parser docker
    reserve_data on
    preserve_key on

[OUTPUT]
    Name            loki
    Match           docker.*
    Host            loki
    Port            3100
    Labels          service=$service,container=$container_name
    Line_Format     json
